import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedSe_SpotSilla_MastermindFlowMesa1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedReadingBooksWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedByJonathanWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedByRyantieWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedIcons8save642Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedRecentlyviewWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/Generated3WaystoUseExperientialLearningtoBoostYourCareer1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedAWiseCertificationWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedStudentProjectsWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedPngfind1Widget5.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedHowtocreateaproductivestudyspaceathome_1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/Generated890Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedProjectsWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedLessonWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/Generated980Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/Generated20kWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedDiscussionThingsWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/Generated326537_backup_cloud_upload_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall8widget/generated/GeneratedPngfind2Widget4.dart';

/* Frame Android Small - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget5(),
          ),
          Positioned(
            left: 31.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 11.448980331420898,
            height: 20.0,
            child: GeneratedPngfind2Widget4(),
          ),
          Positioned(
            left: 297.0,
            top: 28.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save642Widget1(),
          ),
          Positioned(
            left: 55.0,
            top: 590.0,
            right: null,
            bottom: null,
            width: 85.0,
            height: 23.0,
            child: GeneratedLessonWidget1(),
          ),
          Positioned(
            left: 217.0,
            top: 590.0,
            right: null,
            bottom: null,
            width: 85.0,
            height: 23.0,
            child: GeneratedProjectsWidget(),
          ),
          Positioned(
            left: 196.0,
            top: 617.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 2.0,
            child: GeneratedLine4Widget1(),
          ),
          Positioned(
            left: 31.0,
            top: 68.0,
            right: null,
            bottom: null,
            width: 228.0,
            height: 33.0,
            child: GeneratedStudentProjectsWidget(),
          ),
          Positioned(
            left: 30.0,
            top: 113.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 134.0,
            child: GeneratedHowtocreateaproductivestudyspaceathome_1Widget(),
          ),
          Positioned(
            left: 41.0,
            top: 197.0,
            right: null,
            bottom: null,
            width: 109.0,
            height: 35.0,
            child: GeneratedReadingBooksWidget(),
          ),
          Positioned(
            left: 72.0,
            top: 216.0,
            right: null,
            bottom: null,
            width: 109.0,
            height: 35.0,
            child: GeneratedRecentlyviewWidget(),
          ),
          Positioned(
            left: 41.0,
            top: 220.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: Generated326537_backup_cloud_upload_icon1Widget(),
          ),
          Positioned(
            left: 262.0,
            top: 213.0,
            right: null,
            bottom: null,
            width: 64.0,
            height: 24.0,
            child: GeneratedRectangle15Widget(),
          ),
          Positioned(
            left: 294.0,
            top: 209.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 38.0,
            child: Generated20kWidget(),
          ),
          Positioned(
            left: 29.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 134.0,
            child: GeneratedSe_SpotSilla_MastermindFlowMesa1Widget(),
          ),
          Positioned(
            left: 41.0,
            top: 346.0,
            right: null,
            bottom: null,
            width: 157.0,
            height: 35.0,
            child: GeneratedAWiseCertificationWidget(),
          ),
          Positioned(
            left: 67.0,
            top: 366.0,
            right: null,
            bottom: null,
            width: 109.0,
            height: 35.0,
            child: GeneratedByRyantieWidget(),
          ),
          Positioned(
            left: 29.0,
            top: 417.0,
            right: null,
            bottom: null,
            width: 300.0,
            height: 143.0,
            child:
                Generated3WaystoUseExperientialLearningtoBoostYourCareer1Widget(),
          ),
          Positioned(
            left: 41.0,
            top: 506.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 35.0,
            child: GeneratedDiscussionThingsWidget(),
          ),
          Positioned(
            left: 67.0,
            top: 526.0,
            right: null,
            bottom: null,
            width: 109.0,
            height: 35.0,
            child: GeneratedByJonathanWidget(),
          ),
          Positioned(
            left: 262.0,
            top: 367.0,
            right: null,
            bottom: null,
            width: 64.0,
            height: 24.0,
            child: GeneratedRectangle16Widget(),
          ),
          Positioned(
            left: 295.0,
            top: 362.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 38.0,
            child: Generated980Widget(),
          ),
          Positioned(
            left: 262.0,
            top: 526.0,
            right: null,
            bottom: null,
            width: 64.0,
            height: 24.0,
            child: GeneratedRectangle17Widget(),
          ),
          Positioned(
            left: 295.0,
            top: 522.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 38.0,
            child: Generated890Widget(),
          )
        ]),
      ),
    ));
  }
}
