import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall1widget/generated/GeneratedLearning_App__3_removebgpreview1Widget.dart';

/* Frame Android Small - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedAndroidSmall2Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 360.0,
          height: 640.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 153, 0, 225),
                  ),
                ),
                Positioned(
                  left: 30.0,
                  top: 145.0,
                  right: null,
                  bottom: null,
                  width: 300.0,
                  height: 300.0,
                  child: GeneratedLearning_App__3_removebgpreview1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
