import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedPngfind1Widget7.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedRealisticDesignwithColorandExpressionWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/Generated3671703_bookmark_outline_icon12Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/Generated_2Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedHandmadeTexturesandOrnamentsforDesignersWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedFlutterbyBussinessCardDesignWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedIcons8save648Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedDesignClassesWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedIcons8save649Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedPngfind2Widget5.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/Generated9idesDIYrepressurPinterest_ShakeMyBlog1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedCreativeDigitalIlustrationlearntouseAdobeFrescoWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedIcons8save647Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedFlutterbyBusinessCard1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedDesignaposterwithanAbstractindexcardeffectWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedDownload11Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedRBFPosterDesignbyHereandNow1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/Generated4092559_search_magnifier_mobileui_zoom_icon3Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/GeneratedDesignWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall10widget/generated/Generated3671703_bookmark_outline_icon11Widget.dart';

/* Frame Android Small - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: null,
            top: 27.0,
            right: null,
            bottom: null,
            width: 250.0,
            height: 39.0,
            child: TransformHelper.translate(
                x: 3.00, y: 0.00, z: 0, child: GeneratedSearchWidget()),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget7(),
          ),
          Positioned(
            left: 31.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 11.448980331420898,
            height: 20.0,
            child: GeneratedPngfind2Widget5(),
          ),
          Positioned(
            left: 37.0,
            top: 85.0,
            right: null,
            bottom: null,
            width: 293.0,
            height: 38.0,
            child: GeneratedRectangle15Widget1(),
          ),
          Positioned(
            left: 52.0,
            top: 92.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child:
                Generated4092559_search_magnifier_mobileui_zoom_icon3Widget(),
          ),
          Positioned(
            left: 90.0,
            top: 89.0,
            right: null,
            bottom: null,
            width: 206.0,
            height: 36.0,
            child: GeneratedDesignWidget1(),
          ),
          Positioned(
            left: 30.0,
            top: 137.0,
            right: null,
            bottom: null,
            width: 214.0,
            height: 24.0,
            child: GeneratedDesignClassesWidget(),
          ),
          Positioned(
            left: 31.0,
            top: 170.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 67.0,
            child: Generated9idesDIYrepressurPinterest_ShakeMyBlog1Widget(),
          ),
          Positioned(
            left: 30.0,
            top: 258.0,
            right: null,
            bottom: null,
            width: 91.0,
            height: 66.0,
            child: GeneratedRBFPosterDesignbyHereandNow1Widget(),
          ),
          Positioned(
            left: 31.0,
            top: 346.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 66.0,
            child: Generated_2Widget1(),
          ),
          Positioned(
            left: 31.0,
            top: 436.0,
            right: null,
            bottom: null,
            width: 90.0,
            height: 68.0,
            child: GeneratedDownload11Widget(),
          ),
          Positioned(
            left: 30.0,
            top: 530.0,
            right: null,
            bottom: null,
            width: 91.0,
            height: 68.0,
            child: GeneratedFlutterbyBusinessCard1Widget(),
          ),
          Positioned(
            left: 130.0,
            top: 157.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 67.0,
            child: GeneratedHandmadeTexturesandOrnamentsforDesignersWidget(),
          ),
          Positioned(
            left: 130.0,
            top: 243.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 67.0,
            child: GeneratedDesignaposterwithanAbstractindexcardeffectWidget(),
          ),
          Positioned(
            left: 130.0,
            top: 338.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 67.0,
            child: GeneratedRealisticDesignwithColorandExpressionWidget1(),
          ),
          Positioned(
            left: 130.0,
            top: 426.0,
            right: null,
            bottom: null,
            width: 203.0,
            height: 67.0,
            child:
                GeneratedCreativeDigitalIlustrationlearntouseAdobeFrescoWidget(),
          ),
          Positioned(
            left: 130.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 203.0,
            height: 67.0,
            child: GeneratedFlutterbyBussinessCardDesignWidget(),
          ),
          Positioned(
            left: 311.0,
            top: 189.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: Generated3671703_bookmark_outline_icon11Widget(),
          ),
          Positioned(
            left: 311.0,
            top: 287.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: Generated3671703_bookmark_outline_icon12Widget(),
          ),
          Positioned(
            left: 311.0,
            top: 383.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save647Widget(),
          ),
          Positioned(
            left: 311.0,
            top: 474.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save648Widget(),
          ),
          Positioned(
            left: 311.0,
            top: 562.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save649Widget(),
          )
        ]),
      ),
    ));
  }
}
