import 'package:flutter/material.dart';

/* Rectangle Premium Vector _ Woman working at laptop from home illustration 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPremiumVector_Womanworkingatlaptopfromhomeillustration1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 267.0,
      height: 256.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(200.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(200.0),
        child: Image.asset(
          "assets/images/06dd40c349f5aabda3164228e32de9ca7003a0af.png",
          color: null,
          fit: BoxFit.cover,
          width: 267.0,
          height: 256.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
