import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedDownload1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedWhatyouwanttolearntodayWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/Generated9055329_bxs_home_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedDuringDivorceFocusOnWhatYouWant1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedCookingWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedOliviaRodrigue2weeksagoWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedBasedonyouractivityWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/Generated753124_microwave_oven_cook_cooking_kitchen_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/Generated_1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedHowtowriteaWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedRecentClassWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/Generated3669295_ic_white_filled_play_circle_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedPhotographyCaptureandSharedYourLifeWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedArtsWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedRecomendedclosestforyouWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedPngfind1Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedJourneyWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/Generated352250_brush_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedRealisticDesignWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedSearchclassesWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/Generated4092559_search_magnifier_mobileui_zoom_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/GeneratedWelcomeFifiWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall5widget/generated/Generated8541567_book_open_reading_icon1Widget.dart';

/* Frame Android Small - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget2(),
          ),
          Positioned(
            left: 25.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 159.0,
            height: 34.0,
            child: GeneratedWelcomeFifiWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 59.0,
            right: null,
            bottom: null,
            width: 270.0,
            height: 24.0,
            child: GeneratedWhatyouwanttolearntodayWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 389.0,
            right: null,
            bottom: null,
            width: 195.0,
            height: 24.0,
            child: GeneratedBasedonyouractivityWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 232.0,
            right: null,
            bottom: null,
            width: 103.0,
            height: 24.0,
            child: GeneratedRecentClassWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 371.0,
            right: null,
            bottom: null,
            width: 214.0,
            height: 24.0,
            child: GeneratedRecomendedclosestforyouWidget(),
          ),
          Positioned(
            left: 20.0,
            top: 109.0,
            right: null,
            bottom: null,
            width: 320.0,
            height: 38.0,
            child: GeneratedRectangle8Widget(),
          ),
          Positioned(
            left: 37.0,
            top: 115.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child:
                Generated4092559_search_magnifier_mobileui_zoom_icon1Widget(),
          ),
          Positioned(
            left: 73.0,
            top: 113.0,
            right: null,
            bottom: null,
            width: 187.0,
            height: 32.0,
            child: GeneratedSearchclassesWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 132.0,
            height: 44.0,
            child: GeneratedRectangle9Widget(),
          ),
          Positioned(
            left: 193.0,
            top: 166.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 44.0,
            child: GeneratedRectangle10Widget(),
          ),
          Positioned(
            left: 78.0,
            top: 171.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedCookingWidget(),
          ),
          Positioned(
            left: 248.0,
            top: 173.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedArtsWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 273.0,
            right: null,
            bottom: null,
            width: 315.0,
            height: 90.0,
            child: GeneratedRectangle11Widget(),
          ),
          Positioned(
            left: 25.0,
            top: 260.0,
            right: null,
            bottom: null,
            width: 92.69999694824219,
            height: 90.0,
            child: GeneratedDuringDivorceFocusOnWhatYouWant1Widget(),
          ),
          Positioned(
            left: 127.0,
            top: 253.0,
            right: null,
            bottom: null,
            width: 228.0,
            height: 48.0,
            child: GeneratedPhotographyCaptureandSharedYourLifeWidget(),
          ),
          Positioned(
            left: 126.0,
            top: 288.0,
            right: null,
            bottom: null,
            width: 202.0,
            height: 51.0,
            child: GeneratedOliviaRodrigue2weeksagoWidget(),
          ),
          Positioned(
            left: 51.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Generated9055329_bxs_home_icon1Widget(),
          ),
          Positioned(
            left: 268.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Generated8541567_book_open_reading_icon1Widget(),
          ),
          Positioned(
            left: 49.0,
            top: 606.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 24.0,
            child: GeneratedHomeWidget(),
          ),
          Positioned(
            left: 256.0,
            top: 606.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 24.0,
            child: GeneratedJourneyWidget(),
          ),
          Positioned(
            left: 49.0,
            top: 282.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 50.0,
            child: Generated3669295_ic_white_filled_play_circle_icon1Widget(),
          ),
          Positioned(
            left: 126.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 190.0,
            height: 5.0,
            child: GeneratedLine1Widget(),
          ),
          Positioned(
            left: 126.0,
            top: 343.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 5.0,
            child: GeneratedLine2Widget(),
          ),
          Positioned(
            left: 28.0,
            top: 417.0,
            right: null,
            bottom: null,
            width: 140.0,
            height: 130.0,
            child: Generated_1Widget(),
          ),
          Positioned(
            left: 198.0,
            top: 414.0,
            right: null,
            bottom: null,
            width: 126.0,
            height: 133.0,
            child: GeneratedDownload1Widget(),
          ),
          Positioned(
            left: 28.0,
            top: 550.0,
            right: null,
            bottom: null,
            width: 148.0,
            height: 20.0,
            child: GeneratedRealisticDesignWidget(),
          ),
          Positioned(
            left: 200.0,
            top: 550.0,
            right: null,
            bottom: null,
            width: 124.0,
            height: 20.0,
            child: GeneratedHowtowriteaWidget(),
          ),
          Positioned(
            left: 34.0,
            top: 164.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child:
                Generated753124_microwave_oven_cook_cooking_kitchen_icon1Widget(),
          ),
          Positioned(
            left: 201.0,
            top: 168.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child: Generated352250_brush_icon1Widget(),
          ),
          Positioned(
            left: 295.0,
            top: 27.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 38.0,
            child: GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget(),
          )
        ]),
      ),
    ));
  }
}
