import 'package:flutter/material.dart';

/* Rectangle 3994400_arrow_forward_navigation_next_right_icon 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated3994400_arrow_forward_navigation_next_right_icon1Widget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 20.0,
      height: 20.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/51cd88f2ced4e7c9b98e35b9ea14069c26bd1826.png",
          color: null,
          fit: BoxFit.cover,
          width: 20.0,
          height: 20.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
