import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/Generated352250_brush_icon2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/Generated753124_microwave_oven_cook_cooking_kitchen_icon2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/Generated3669295_ic_white_filled_play_circle_icon2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedWelcomeFifiWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedOliviaRodrigue2weeksagoWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/Generated_2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedRealisticDesignWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedRecomendedclosestforyouWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedContinueyourclassWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/Generated8541567_book_open_reading_icon1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedJourneyWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedIcons8save641Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedPngfind1Widget3.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedBasedonyouractivityWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/Generated9055329_bxs_home_icon1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedArtsWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedDownload2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedHowtowriteaWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedPhotographyCaptureandSharedYourLifeWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedDuringDivorceFocusOnWhatYouWant2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall6widget/generated/GeneratedCookingWidget1.dart';

/* Frame Android Small - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget3(),
          ),
          Positioned(
            left: 25.0,
            top: 32.0,
            right: null,
            bottom: null,
            width: 101.0,
            height: 23.0,
            child: GeneratedWelcomeFifiWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 59.0,
            right: null,
            bottom: null,
            width: 270.0,
            height: 24.0,
            child: GeneratedContinueyourclassWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 369.0,
            right: null,
            bottom: null,
            width: 214.0,
            height: 24.0,
            child: GeneratedRecomendedclosestforyouWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 302.0,
            right: null,
            bottom: null,
            width: 132.0,
            height: 44.0,
            child: GeneratedRectangle9Widget1(),
          ),
          Positioned(
            left: 193.0,
            top: 298.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 44.0,
            child: GeneratedRectangle10Widget1(),
          ),
          Positioned(
            left: 76.0,
            top: 308.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedCookingWidget1(),
          ),
          Positioned(
            left: 257.0,
            top: 303.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedArtsWidget1(),
          ),
          Positioned(
            left: 51.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Generated9055329_bxs_home_icon1Widget1(),
          ),
          Positioned(
            left: 274.0,
            top: 576.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Generated8541567_book_open_reading_icon1Widget1(),
          ),
          Positioned(
            left: 48.0,
            top: 606.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 24.0,
            child: GeneratedHomeWidget1(),
          ),
          Positioned(
            left: 266.0,
            top: 606.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 24.0,
            child: GeneratedJourneyWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 96.0,
            right: null,
            bottom: null,
            width: 279.0,
            height: 141.0,
            child: GeneratedDuringDivorceFocusOnWhatYouWant2Widget(),
          ),
          Positioned(
            left: 143.0,
            top: 129.0,
            right: null,
            bottom: null,
            width: 50.0,
            height: 50.0,
            child: Generated3669295_ic_white_filled_play_circle_icon2Widget(),
          ),
          Positioned(
            left: 25.0,
            top: 209.0,
            right: null,
            bottom: null,
            width: 279.0,
            height: 76.0,
            child: GeneratedRectangle12Widget(),
          ),
          Positioned(
            left: 25.0,
            top: 214.0,
            right: null,
            bottom: null,
            width: 228.0,
            height: 48.0,
            child: GeneratedPhotographyCaptureandSharedYourLifeWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 209.0,
            right: null,
            bottom: null,
            width: 279.0,
            height: 5.0,
            child: GeneratedLine3Widget(),
          ),
          Positioned(
            left: 25.0,
            top: 209.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 5.0,
            child: GeneratedLine3Widget1(),
          ),
          Positioned(
            left: 25.0,
            top: 246.0,
            right: null,
            bottom: null,
            width: 202.0,
            height: 51.0,
            child: GeneratedOliviaRodrigue2weeksagoWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 386.0,
            right: null,
            bottom: null,
            width: 195.0,
            height: 24.0,
            child: GeneratedBasedonyouractivityWidget1(),
          ),
          Positioned(
            left: 25.0,
            top: 413.0,
            right: null,
            bottom: null,
            width: 140.0,
            height: 130.0,
            child: Generated_2Widget(),
          ),
          Positioned(
            left: 25.0,
            top: 551.0,
            right: null,
            bottom: null,
            width: 148.0,
            height: 20.0,
            child: GeneratedRealisticDesignWidget1(),
          ),
          Positioned(
            left: 197.0,
            top: 410.0,
            right: null,
            bottom: null,
            width: 126.0,
            height: 133.0,
            child: GeneratedDownload2Widget(),
          ),
          Positioned(
            left: 201.0,
            top: 551.0,
            right: null,
            bottom: null,
            width: 124.0,
            height: 20.0,
            child: GeneratedHowtowriteaWidget1(),
          ),
          Positioned(
            left: 279.0,
            top: 214.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save641Widget(),
          ),
          Positioned(
            left: 33.0,
            top: 304.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child:
                Generated753124_microwave_oven_cook_cooking_kitchen_icon2Widget(),
          ),
          Positioned(
            left: 205.0,
            top: 298.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child: Generated352250_brush_icon2Widget(),
          ),
          Positioned(
            left: 292.0,
            top: 26.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 38.0,
            child: GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget1(),
          )
        ]),
      ),
    ));
  }
}
