import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall13widget/generated/GeneratedPngfind1Widget10.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall13widget/generated/GeneratedResetPasswordWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall13widget/generated/GeneratedPngfind2Widget8.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall13widget/generated/GeneratedResetPasswordWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall13widget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall13widget/generated/GeneratedNewPasswordWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall13widget/generated/GeneratedRectangle19Widget.dart';

/* Frame Android Small - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: 88.0,
            top: 265.0,
            right: null,
            bottom: null,
            width: 198.0,
            height: 40.0,
            child: GeneratedRectangle1Widget3(),
          ),
          Positioned(
            left: 125.0,
            top: 275.0,
            right: null,
            bottom: null,
            width: 139.0,
            height: 24.0,
            child: GeneratedResetPasswordWidget(),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget10(),
          ),
          Positioned(
            left: 31.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 11.448980331420898,
            height: 20.0,
            child: GeneratedPngfind2Widget8(),
          ),
          Positioned(
            left: null,
            top: 26.0,
            right: null,
            bottom: null,
            width: 247.0,
            height: 36.0,
            child: TransformHelper.translate(
                x: 0.50, y: 0.00, z: 0, child: GeneratedResetPasswordWidget1()),
          ),
          Positioned(
            left: 44.0,
            top: 130.0,
            right: null,
            bottom: null,
            width: 273.0,
            height: 45.0,
            child: GeneratedRectangle19Widget(),
          ),
          Positioned(
            left: 70.0,
            top: 144.0,
            right: null,
            bottom: null,
            width: 96.0,
            height: 18.0,
            child: GeneratedNewPasswordWidget(),
          )
        ]),
      ),
    ));
  }
}
