import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedAlreadyhaveanaccountWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedBysigningupyouagreetothetermsofserviceandprivacypolicyW.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedPngfind2Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedPngfind1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedCreateAccountWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall4widget/generated/GeneratedRectangle7Widget.dart';

/* Frame Android Small - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedAndroidSmall5Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 360.0,
          height: 640.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 233, 231, 234),
                  ),
                ),
                Positioned(
                  left: null,
                  top: 27.0,
                  right: null,
                  bottom: null,
                  width: 247.0,
                  height: 36.0,
                  child: TransformHelper.translate(
                      x: 1.50, y: 0.00, z: 0, child: GeneratedSIGNUPWidget()),
                ),
                Positioned(
                  left: 81.0,
                  top: 384.0,
                  right: null,
                  bottom: null,
                  width: 198.0,
                  height: 40.0,
                  child: GeneratedRectangle1Widget1(),
                ),
                Positioned(
                  left: 114.0,
                  top: 393.0,
                  right: null,
                  bottom: null,
                  width: 139.0,
                  height: 24.0,
                  child: GeneratedCreateAccountWidget(),
                ),
                Positioned(
                  left: -255.0,
                  top: -445.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 34.9376106262207,
                  child: GeneratedPngfind1Widget1(),
                ),
                Positioned(
                  left: 31.0,
                  top: 33.0,
                  right: null,
                  bottom: null,
                  width: 11.448980331420898,
                  height: 20.0,
                  child: GeneratedPngfind2Widget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 115.0,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 37.0,
                  child: GeneratedRectangle4Widget(),
                ),
                Positioned(
                  left: 37.0,
                  top: 181.0,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 37.0,
                  child: GeneratedRectangle5Widget(),
                ),
                Positioned(
                  left: 37.0,
                  top: 249.0,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 37.0,
                  child: GeneratedRectangle6Widget(),
                ),
                Positioned(
                  left: 47.0,
                  top: 119.0,
                  right: null,
                  bottom: null,
                  width: 230.0,
                  height: 34.0,
                  child: GeneratedUsernameWidget(),
                ),
                Positioned(
                  left: 47.0,
                  top: 188.0,
                  right: null,
                  bottom: null,
                  width: 269.0,
                  height: 28.0,
                  child: GeneratedEmailWidget(),
                ),
                Positioned(
                  left: 47.0,
                  top: 258.0,
                  right: null,
                  bottom: null,
                  width: 68.0,
                  height: 21.0,
                  child: GeneratedPasswordWidget(),
                ),
                Positioned(
                  left: 43.0,
                  top: 312.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 15.0,
                  child: GeneratedRectangle7Widget(),
                ),
                Positioned(
                  left: 69.0,
                  top: 309.0,
                  right: null,
                  bottom: null,
                  width: 262.0,
                  height: 25.0,
                  child:
                      GeneratedBysigningupyouagreetothetermsofserviceandprivacypolicyW(),
                ),
                Positioned(
                  left: 43.0,
                  top: 436.0,
                  right: null,
                  bottom: null,
                  width: 282.0,
                  height: 30.0,
                  child: GeneratedAlreadyhaveanaccountWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
