import 'package:flutter/material.dart';

/* Rectangle 20 Weird Things That Only Girls Who Wear Glasses Can Relate To 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated20WeirdThingsThatOnlyGirlsWhoWearGlassesCanRelateTo1Wid
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 40.0,
      height: 40.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: Image.asset(
          "assets/images/294280ef1c7dbe9508c79e4124e781d71897cd97.png",
          color: null,
          fit: BoxFit.cover,
          width: 40.0,
          height: 40.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
