import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedDownload2Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedPhotographyCaptureandSharedYourLifeWidget3.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedIcons8save646Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedFlutterbyBussinessCardDesignWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedIcons8save643Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedIcons8save642Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedFavoriteClassWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedFlutterbyBusinessCard2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/Generated_2Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedHowtowriteabeautifulsongWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedIcons8save644Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedRealisticDesignwithColorandExpressionWidget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedCreativeDigitalIlustrationlearntouseAdobeFrescoWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedIcons8save645Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedPngfind1Widget8.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedPngfind2Widget6.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall11widget/generated/GeneratedDownload11Widget1.dart';

/* Frame Android Small - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: null,
            top: 27.0,
            right: null,
            bottom: null,
            width: 247.0,
            height: 36.0,
            child: TransformHelper.translate(
                x: 1.50, y: 0.00, z: 0, child: GeneratedFavoriteClassWidget()),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget8(),
          ),
          Positioned(
            left: 31.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 11.448980331420898,
            height: 20.0,
            child: GeneratedPngfind2Widget6(),
          ),
          Positioned(
            left: 30.0,
            top: 200.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 73.0,
            child: Generated_2Widget2(),
          ),
          Positioned(
            left: 31.0,
            top: 298.0,
            right: null,
            bottom: null,
            width: 99.0,
            height: 73.0,
            child: GeneratedDownload11Widget1(),
          ),
          Positioned(
            left: 136.0,
            top: 90.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 67.0,
            child: GeneratedPhotographyCaptureandSharedYourLifeWidget3(),
          ),
          Positioned(
            left: 136.0,
            top: 187.0,
            right: null,
            bottom: null,
            width: 193.0,
            height: 67.0,
            child: GeneratedRealisticDesignwithColorandExpressionWidget2(),
          ),
          Positioned(
            left: 136.0,
            top: 283.0,
            right: null,
            bottom: null,
            width: 203.0,
            height: 67.0,
            child:
                GeneratedCreativeDigitalIlustrationlearntouseAdobeFrescoWidget1(),
          ),
          Positioned(
            left: 136.0,
            top: 386.0,
            right: null,
            bottom: null,
            width: 203.0,
            height: 67.0,
            child: GeneratedFlutterbyBussinessCardDesignWidget1(),
          ),
          Positioned(
            left: 30.0,
            top: 398.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 68.0,
            child: GeneratedFlutterbyBusinessCard2Widget(),
          ),
          Positioned(
            left: 30.0,
            top: 491.0,
            right: null,
            bottom: null,
            width: 100.0,
            height: 68.0,
            child: GeneratedDownload2Widget1(),
          ),
          Positioned(
            left: 136.0,
            top: 482.0,
            right: null,
            bottom: null,
            width: 146.0,
            height: 57.0,
            child: GeneratedHowtowriteabeautifulsongWidget1(),
          ),
          Positioned(
            left: 303.0,
            top: 135.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save642Widget2(),
          ),
          Positioned(
            left: 303.0,
            top: 232.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save643Widget(),
          ),
          Positioned(
            left: 303.0,
            top: 334.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save644Widget(),
          ),
          Positioned(
            left: 303.0,
            top: 435.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save645Widget(),
          ),
          Positioned(
            left: 303.0,
            top: 524.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child: GeneratedIcons8save646Widget(),
          )
        ]),
      ),
    ));
  }
}
