import 'package:flutter/material.dart';

/* Rectangle 211876_play_icon 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated211876_play_icon1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 25.0,
      height: 25.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/109795ea240d9fbf9d00946d8f8cb1f6ff915ab8.png",
          color: null,
          fit: BoxFit.cover,
          width: 25.0,
          height: 25.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
