import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedBrowseofclassesormentorsWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedMusicWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated_1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated6602563_design_graphic_picture_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedCookingWidget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated4092559_search_magnifier_mobileui_zoom_icon2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedLearnfromthemostviewedWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedPngfind1Widget6.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedDownload1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedSearchclassesWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated211867_note_music_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated8541567_book_open_reading_icon1Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedHowtowriteabeautifulsongWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated9055329_bxs_home_icon1Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedDesignWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedHomeWidget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedPopularClassesWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedRealisticDesignwithColorandExpressionWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedDiscoverWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedJourneyWidget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/GeneratedArtsWidget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated352250_brush_icon1Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall9widget/generated/Generated753124_microwave_oven_cook_cooking_kitchen_icon1Widget1.dart';

/* Frame Android Small - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget6(),
          ),
          Positioned(
            left: 25.0,
            top: 302.0,
            right: null,
            bottom: null,
            width: 195.0,
            height: 24.0,
            child: GeneratedLearnfromthemostviewedWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 282.0,
            right: null,
            bottom: null,
            width: 214.0,
            height: 24.0,
            child: GeneratedPopularClassesWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 148.0,
            right: null,
            bottom: null,
            width: 132.0,
            height: 44.0,
            child: GeneratedRectangle9Widget2(),
          ),
          Positioned(
            left: 193.0,
            top: 148.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 44.0,
            child: GeneratedRectangle10Widget2(),
          ),
          Positioned(
            left: 193.0,
            top: 214.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 44.0,
            child: GeneratedRectangle14Widget1(),
          ),
          Positioned(
            left: 27.0,
            top: 214.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 44.0,
            child: GeneratedRectangle13Widget1(),
          ),
          Positioned(
            left: 78.0,
            top: 155.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedCookingWidget2(),
          ),
          Positioned(
            left: 81.0,
            top: 223.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedMusicWidget(),
          ),
          Positioned(
            left: 246.0,
            top: 155.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedArtsWidget2(),
          ),
          Positioned(
            left: 246.0,
            top: 222.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 36.0,
            child: GeneratedDesignWidget(),
          ),
          Positioned(
            left: 51.0,
            top: 578.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Generated9055329_bxs_home_icon1Widget2(),
          ),
          Positioned(
            left: 235.0,
            top: 578.0,
            right: null,
            bottom: null,
            width: 30.0,
            height: 30.0,
            child: Generated8541567_book_open_reading_icon1Widget2(),
          ),
          Positioned(
            left: 49.0,
            top: 608.0,
            right: null,
            bottom: null,
            width: 55.0,
            height: 24.0,
            child: GeneratedHomeWidget2(),
          ),
          Positioned(
            left: 226.0,
            top: 608.0,
            right: null,
            bottom: null,
            width: 74.0,
            height: 24.0,
            child: GeneratedJourneyWidget2(),
          ),
          Positioned(
            left: 28.0,
            top: 346.0,
            right: null,
            bottom: null,
            width: 140.0,
            height: 130.0,
            child: Generated_1Widget1(),
          ),
          Positioned(
            left: 198.0,
            top: 347.0,
            right: null,
            bottom: null,
            width: 126.0,
            height: 133.0,
            child: GeneratedDownload1Widget1(),
          ),
          Positioned(
            left: 32.0,
            top: 482.0,
            right: null,
            bottom: null,
            width: 137.0,
            height: 34.0,
            child: GeneratedRealisticDesignwithColorandExpressionWidget(),
          ),
          Positioned(
            left: 201.0,
            top: 487.0,
            right: null,
            bottom: null,
            width: 138.0,
            height: 20.0,
            child: GeneratedHowtowriteabeautifulsongWidget(),
          ),
          Positioned(
            left: 25.0,
            top: 17.0,
            right: null,
            bottom: null,
            width: 231.0,
            height: 36.0,
            child: GeneratedDiscoverWidget(),
          ),
          Positioned(
            left: 28.0,
            top: 41.0,
            right: null,
            bottom: null,
            width: 282.0,
            height: 33.0,
            child: GeneratedBrowseofclassesormentorsWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 87.0,
            right: null,
            bottom: null,
            width: 320.0,
            height: 38.0,
            child: GeneratedRectangle12Widget1(),
          ),
          Positioned(
            left: 72.0,
            top: 91.0,
            right: null,
            bottom: null,
            width: 282.0,
            height: 33.0,
            child: GeneratedSearchclassesWidget1(),
          ),
          Positioned(
            left: 39.0,
            top: 94.0,
            right: null,
            bottom: null,
            width: 25.0,
            height: 25.0,
            child:
                Generated4092559_search_magnifier_mobileui_zoom_icon2Widget(),
          ),
          Positioned(
            left: 32.0,
            top: 150.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child:
                Generated753124_microwave_oven_cook_cooking_kitchen_icon1Widget1(),
          ),
          Positioned(
            left: 32.0,
            top: 216.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child: Generated211867_note_music_icon1Widget(),
          ),
          Positioned(
            left: 201.0,
            top: 149.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child: Generated352250_brush_icon1Widget1(),
          ),
          Positioned(
            left: 201.0,
            top: 215.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 40.0,
            child: Generated6602563_design_graphic_picture_icon1Widget(),
          ),
          Positioned(
            left: 295.0,
            top: 26.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 38.0,
            child: GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget2(),
          )
        ]),
      ),
    ));
  }
}
