import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedAboutMeWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedAboutUsWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedAccountSettingWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedPngfind1Widget9.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedDeleteAccountWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedLOGOUTWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedZulfiantiRahmawatiAviviashilah14gmailcomWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedPrivacyPolicyWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedHelpCenterWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget3.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall12widget/generated/GeneratedPngfind2Widget7.dart';

/* Frame Android Small - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: null,
            top: 27.0,
            right: null,
            bottom: null,
            width: 247.0,
            height: 36.0,
            child: TransformHelper.translate(
                x: 1.50, y: 0.00, z: 0, child: GeneratedAboutMeWidget()),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget9(),
          ),
          Positioned(
            left: 31.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 11.448980331420898,
            height: 20.0,
            child: GeneratedPngfind2Widget7(),
          ),
          Positioned(
            left: 0.0,
            top: 83.0,
            right: null,
            bottom: null,
            width: 360.0,
            height: 166.0,
            child: GeneratedRectangle18Widget(),
          ),
          Positioned(
            left: 34.0,
            top: 132.0,
            right: null,
            bottom: null,
            width: 60.0,
            height: 61.62162399291992,
            child: GeneratedE41212263_ZulfiantiRahmawati_TIF1Widget3(),
          ),
          Positioned(
            left: 111.0,
            top: 132.0,
            right: null,
            bottom: null,
            width: 210.0,
            height: 57.0,
            child: GeneratedZulfiantiRahmawatiAviviashilah14gmailcomWidget(),
          ),
          Positioned(
            left: 22.0,
            top: 269.0,
            right: null,
            bottom: null,
            width: 189.0,
            height: 42.0,
            child: GeneratedAccountSettingWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 312.0,
            right: null,
            bottom: null,
            width: 189.0,
            height: 42.0,
            child: GeneratedPrivacyPolicyWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 358.0,
            right: null,
            bottom: null,
            width: 189.0,
            height: 42.0,
            child: GeneratedAboutUsWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 398.0,
            right: null,
            bottom: null,
            width: 189.0,
            height: 42.0,
            child: GeneratedHelpCenterWidget(),
          ),
          Positioned(
            left: 23.0,
            top: 443.0,
            right: null,
            bottom: null,
            width: 183.0,
            height: 37.0,
            child: GeneratedDeleteAccountWidget(),
          ),
          Positioned(
            left: 82.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 198.0,
            height: 40.0,
            child: GeneratedRectangle8Widget1(),
          ),
          Positioned(
            left: 100.0,
            top: 525.0,
            right: null,
            bottom: null,
            width: 165.0,
            height: 26.0,
            child: GeneratedLOGOUTWidget(),
          )
        ]),
      ),
    ));
  }
}
