import 'package:flutter/material.dart';

/* Rectangle During Divorce Focus On What You Want 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDuringDivorceFocusOnWhatYouWant1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 100.0,
      height: 73.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(10.0),
        child: Image.asset(
          "assets/images/ef8e3e5d0577a45b68ce21f2ed65fd42f18dec9f.png",
          color: null,
          fit: BoxFit.cover,
          width: 100.0,
          height: 73.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
