import 'package:flutter/material.dart';

/* Rectangle 2216353_location_locator_map_marker_pin_icon 2
    Autogenerated by FlutLab FTF Generator
  */
class Generated2216353_location_locator_map_marker_pin_icon2Widget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 25.0,
      height: 25.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/2368e09fe6e8f8cae71f4102d598f29cc2fad29a.png",
          color: null,
          fit: BoxFit.cover,
          width: 25.0,
          height: 25.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
