import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall2widget/generated/GeneratedGetclassupdatesandentryinsyncwithvouchersWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall2widget/generated/GeneratedStartLearningWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall2widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall2widget/generated/GeneratedPngfind1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall2widget/generated/GeneratedPngfind2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall2widget/generated/GeneratedMakeLearningAccessibleEverywhereWidget.dart';

/* Frame Android Small - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(30.0),
            child: Container(
              color: Color.fromARGB(255, 233, 231, 234),
            ),
          ),
          Positioned(
            left: 58.0,
            top: 336.0,
            right: null,
            bottom: null,
            width: 248.0,
            height: 102.0,
            child: GeneratedMakeLearningAccessibleEverywhereWidget(),
          ),
          Positioned(
            left: 57.0,
            top: 411.0,
            right: null,
            bottom: null,
            width: 248.0,
            height: 102.0,
            child: GeneratedGetclassupdatesandentryinsyncwithvouchersWidget(),
          ),
          Positioned(
            left: 82.0,
            top: 517.0,
            right: null,
            bottom: null,
            width: 198.0,
            height: 40.0,
            child: GeneratedRectangle1Widget(),
          ),
          Positioned(
            left: 111.0,
            top: 526.0,
            right: null,
            bottom: null,
            width: 139.0,
            height: 24.0,
            child: GeneratedStartLearningWidget(),
          ),
          Positioned(
            left: -255.0,
            top: -445.0,
            right: null,
            bottom: null,
            width: 20.0,
            height: 34.9376106262207,
            child: GeneratedPngfind1Widget(),
          ),
          Positioned(
            left: 31.0,
            top: 33.0,
            right: null,
            bottom: null,
            width: 11.448980331420898,
            height: 20.0,
            child: GeneratedPngfind2Widget(),
          )
        ]),
      ),
    ));
  }
}
