import 'package:flutter/material.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedPngfind2Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedGoogleWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedRememberMeWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedFacebookWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/Generated2993778_facebook_socialmedia_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedDonthaveanAccountCreateaccountWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/Generated7123025_logo_google_g_icon1Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedEnteryourlogindetailstoaccessyouraccountWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedLoginwithyouraccountWidget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/braintechapp/generatedandroidsmall3widget/generated/GeneratedForgetPasswordWidget.dart';

/* Frame Android Small - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedAndroidSmall6Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 360.0,
          height: 640.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 233, 231, 234),
                  ),
                ),
                Positioned(
                  left: 60.0,
                  top: 27.0,
                  right: null,
                  bottom: null,
                  width: 248.0,
                  height: 36.0,
                  child: GeneratedLOGINWidget(),
                ),
                Positioned(
                  left: 65.0,
                  top: 447.0,
                  right: null,
                  bottom: null,
                  width: 237.0,
                  height: 40.0,
                  child: GeneratedRectangle1Widget2(),
                ),
                Positioned(
                  left: 88.0,
                  top: 456.0,
                  right: null,
                  bottom: null,
                  width: 192.0,
                  height: 24.0,
                  child: GeneratedLoginwithyouraccountWidget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 33.0,
                  right: null,
                  bottom: null,
                  width: 11.448979377746582,
                  height: 20.0,
                  child: GeneratedPngfind2Widget2(),
                ),
                Positioned(
                  left: 58.0,
                  top: 85.0,
                  right: null,
                  bottom: null,
                  width: 266.0,
                  height: 74.0,
                  child:
                      GeneratedEnteryourlogindetailstoaccessyouraccountWidget(),
                ),
                Positioned(
                  left: 44.0,
                  top: 181.0,
                  right: null,
                  bottom: null,
                  width: 130.0,
                  height: 36.0,
                  child: GeneratedRectangle2Widget(),
                ),
                Positioned(
                  left: 195.0,
                  top: 180.0,
                  right: null,
                  bottom: null,
                  width: 130.0,
                  height: 36.0,
                  child: GeneratedRectangle3Widget(),
                ),
                Positioned(
                  left: 55.0,
                  top: 184.0,
                  right: null,
                  bottom: null,
                  width: 30.0,
                  height: 30.0,
                  child: Generated2993778_facebook_socialmedia_icon1Widget(),
                ),
                Positioned(
                  left: 88.0,
                  top: 187.0,
                  right: null,
                  bottom: null,
                  width: 71.0,
                  height: 28.0,
                  child: GeneratedFacebookWidget(),
                ),
                Positioned(
                  left: 193.0,
                  top: 173.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 50.0,
                  child: Generated7123025_logo_google_g_icon1Widget(),
                ),
                Positioned(
                  left: 238.0,
                  top: 188.0,
                  right: null,
                  bottom: null,
                  width: 69.0,
                  height: 25.0,
                  child: GeneratedGoogleWidget(),
                ),
                Positioned(
                  left: 37.0,
                  top: 260.0,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 37.0,
                  child: GeneratedRectangle4Widget1(),
                ),
                Positioned(
                  left: 37.0,
                  top: 324.0,
                  right: null,
                  bottom: null,
                  width: 292.0,
                  height: 37.0,
                  child: GeneratedRectangle5Widget1(),
                ),
                Positioned(
                  left: 50.0,
                  top: 264.0,
                  right: null,
                  bottom: null,
                  width: 233.0,
                  height: 33.0,
                  child: GeneratedEmailWidget1(),
                ),
                Positioned(
                  left: 50.0,
                  top: 329.0,
                  right: null,
                  bottom: null,
                  width: 232.0,
                  height: 33.0,
                  child: GeneratedPasswordWidget1(),
                ),
                Positioned(
                  left: 42.0,
                  top: 378.0,
                  right: null,
                  bottom: null,
                  width: 15.0,
                  height: 15.0,
                  child: GeneratedRectangle6Widget1(),
                ),
                Positioned(
                  left: 64.0,
                  top: 375.0,
                  right: null,
                  bottom: null,
                  width: 102.0,
                  height: 25.0,
                  child: GeneratedRememberMeWidget(),
                ),
                Positioned(
                  left: 221.0,
                  top: 374.0,
                  right: null,
                  bottom: null,
                  width: 125.0,
                  height: 25.0,
                  child: GeneratedForgetPasswordWidget(),
                ),
                Positioned(
                  left: 42.0,
                  top: 554.0,
                  right: null,
                  bottom: null,
                  width: 282.0,
                  height: 30.0,
                  child: GeneratedDonthaveanAccountCreateaccountWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
