import 'package:flutter/material.dart';

/* Rectangle 309041_users_group_people_icon 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated309041_users_group_people_icon1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 30.0,
      height: 30.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/6c5a3f9a507c3ff071a824d6e244db5bb9e911df.png",
          color: null,
          fit: BoxFit.cover,
          width: 30.0,
          height: 30.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
