import 'package:flutter/material.dart';

/* Rectangle 2203510_favorite_favourite_heart_love_icon 4
    Autogenerated by FlutLab FTF Generator
  */
class Generated2203510_favorite_favourite_heart_love_icon4Widget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 20.0,
      height: 20.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/7e95fc43cf10b662a8e4718b91b4c458eb46ec35.png",
          color: null,
          fit: BoxFit.cover,
          width: 20.0,
          height: 20.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
