import 'package:flutter/material.dart';

/* Rectangle 1564507_checked_favorite_star_favourite_rating_icon 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated1564507_checked_favorite_star_favourite_rating_icon1Wid
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 25.0,
      height: 25.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/aa0673d45c7148df8ec719bee5eb076213972b57.png",
          color: null,
          fit: BoxFit.cover,
          width: 25.0,
          height: 25.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
